### ISSUE TITLE
Add ability to "add/import proto source" from "github" repo

### ISSUE THREAD

**Issue by ippoippo** [gokums/cli#8]
Google seems to be be extracting out their common proto's into a separate repository.

https://github.com/googleapis/api-common-protos

We would like a way to be able to 

- Import `protos` from a GitHub path
- Configure protoc to be able to build from this source

It seems Google expect us to Clone (so, maybe do a submodule clone) so that we can keep the files up to date.

**Comment by jwall149** [comment]
The easier approach is treating these kind of repo as a submodule, so
1. Add submodule
`git submodule add git@github.com:googleapis/api-common-protos.git proto/x/googleapis`

2. Add into `root.yaml` of your project

**Comment by ippoippo** [comment]
Closing as going to do manually
